apiVersion: v1
kind: Service
metadata:
  name: apm-server
  namespace: apm-demo
spec:
  selector:
    app: apm-server
  ports:
    - protocol: TCP
      port: 8200
      targetPort: 8200

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apm-server
  namespace: apm-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apm-server
  template:
    metadata:
      labels:
        app: apm-server
    spec:
      containers:
        - name: apm-server
          image: docker.elastic.co/apm/apm-server:7.17.0
          ports:
            - containerPort: 8200
          env:
            - name: OUTPUT_ELASTICSEARCH_HOSTS
              value: "elasticsearch:9200"
